### PR TITLE
Create IKKE SPIS SNØ.txt

### PR DESCRIPTION
**Pull request by OmoRashiEnjoyer**
FREE MINECRAFT

### CODE REVIEW

**Comment by OmoRashiEnjoyer** [comment]
Thank you

**Comment by Eliaaj** [comment]
you fag not me

**Comment by OmoRashiEnjoyer** [comment]
UnfoldedEmbellishedGnatcatcher-size_restricted

**Comment by OmoRashiEnjoyer** [comment]
MY AK IS LOCKED AND LOADED

**Comment by OmoRashiEnjoyer** [comment]
YOU BETTER RUN CUNT

**Pull request merged**
